// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(4614);
    // Setup sub module instances
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.ctor(this, "cpu_test_harness.core.m_axi_data");
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.ctor(this, "cpu_test_harness.core.m_axi_inst");
    TOP__cpu_test_harness__DOT__m_axi.ctor(this, "cpu_test_harness.m_axi");
    TOP__instruction_set_pkg.ctor(this, "instruction_set_pkg");
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__cpu_test_harness__DOT__core__DOT__m_axi_data = &TOP__cpu_test_harness__DOT__core__DOT__m_axi_data;
    TOP.__PVT__cpu_test_harness__DOT__core__DOT__m_axi_inst = &TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst;
    TOP.__PVT__cpu_test_harness__DOT__m_axi = &TOP__cpu_test_harness__DOT__m_axi;
    TOP.__PVT__instruction_set_pkg = &TOP__instruction_set_pkg;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.__Vconfigure(true);
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.__Vconfigure(false);
    TOP__cpu_test_harness__DOT__m_axi.__Vconfigure(false);
    TOP__instruction_set_pkg.__Vconfigure(true);
    // Setup scopes
    __Vscopep_TOP = new VerilatedScope{this, "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness = new VerilatedScope{this, "cpu_test_harness", "cpu_test_harness", "cpu_test_harness", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core = new VerilatedScope{this, "cpu_test_harness.core", "core", "cpu", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__alu_inst = new VerilatedScope{this, "cpu_test_harness.core.alu_inst", "alu_inst", "alu", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__arbitrer = new VerilatedScope{this, "cpu_test_harness.core.arbitrer", "arbitrer", "external_req_arbitrer", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__control = new VerilatedScope{this, "cpu_test_harness.core.control", "control", "control", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__data_cache = new VerilatedScope{this, "cpu_test_harness.core.data_cache", "data_cache", "cache", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__instr_cache = new VerilatedScope{this, "cpu_test_harness.core.instr_cache", "instr_cache", "cache", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__ls_decoder = new VerilatedScope{this, "cpu_test_harness.core.ls_decoder", "ls_decoder", "load_store_decoder", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__m_axi_data = new VerilatedScope{this, "cpu_test_harness.core.m_axi_data", "m_axi_data", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__m_axi_inst = new VerilatedScope{this, "cpu_test_harness.core.m_axi_inst", "m_axi_inst", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__reader_inst = new VerilatedScope{this, "cpu_test_harness.core.reader_inst", "reader_inst", "reader", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__reader_inst__mask_apply = new VerilatedScope{this, "cpu_test_harness.core.reader_inst.mask_apply", "mask_apply", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1 = new VerilatedScope{this, "cpu_test_harness.core.reader_inst.mask_apply.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness__core__regfile = new VerilatedScope{this, "cpu_test_harness.core.regfile", "regfile", "regfile", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__core__regfile__unnamedblk1 = new VerilatedScope{this, "cpu_test_harness.core.regfile.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness__core__sign_extender = new VerilatedScope{this, "cpu_test_harness.core.sign_extender", "sign_extender", "signext", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__data_memory = new VerilatedScope{this, "cpu_test_harness.data_memory", "data_memory", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness__m_axi = new VerilatedScope{this, "cpu_test_harness.m_axi", "m_axi", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_cpu_test_harness__regfile = new VerilatedScope{this, "cpu_test_harness.regfile", "regfile", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_cpu_test_harness__unnamedblk1 = new VerilatedScope{this, "cpu_test_harness.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_instruction_set_pkg = new VerilatedScope{this, "instruction_set_pkg", "instruction_set_pkg", "instruction_set_pkg", -9, VerilatedScope::SCOPE_PACKAGE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_cpu_test_harness);
    __Vhier.add(0, __Vscopep_instruction_set_pkg);
    __Vhier.add(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__core);
    __Vhier.add(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__data_memory);
    __Vhier.add(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__m_axi);
    __Vhier.add(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__regfile);
    __Vhier.add(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__unnamedblk1);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__alu_inst);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__arbitrer);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__control);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__data_cache);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__instr_cache);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__ls_decoder);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__m_axi_data);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__m_axi_inst);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__reader_inst);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__regfile);
    __Vhier.add(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__sign_extender);
    __Vhier.add(__Vscopep_cpu_test_harness__core__reader_inst, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply);
    __Vhier.add(__Vscopep_cpu_test_harness__core__reader_inst__mask_apply, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1);
    __Vhier.add(__Vscopep_cpu_test_harness__core__regfile, __Vscopep_cpu_test_harness__core__regfile__unnamedblk1);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_TOP->varInsert("aclk", &(TOP.aclk), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("aresetn", &(TOP.aresetn), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("clk", &(TOP.clk), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_araddr", &(TOP.m_axi_araddr), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("m_axi_arburst", &(TOP.m_axi_arburst), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_TOP->varInsert("m_axi_arid", &(TOP.m_axi_arid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("m_axi_arlen", &(TOP.m_axi_arlen), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("m_axi_arready", &(TOP.m_axi_arready), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_arsize", &(TOP.m_axi_arsize), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_TOP->varInsert("m_axi_arvalid", &(TOP.m_axi_arvalid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_awaddr", &(TOP.m_axi_awaddr), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("m_axi_awburst", &(TOP.m_axi_awburst), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_TOP->varInsert("m_axi_awid", &(TOP.m_axi_awid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("m_axi_awlen", &(TOP.m_axi_awlen), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_TOP->varInsert("m_axi_awready", &(TOP.m_axi_awready), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_awsize", &(TOP.m_axi_awsize), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_TOP->varInsert("m_axi_awvalid", &(TOP.m_axi_awvalid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_bid", &(TOP.m_axi_bid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("m_axi_bready", &(TOP.m_axi_bready), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_bresp", &(TOP.m_axi_bresp), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_TOP->varInsert("m_axi_bvalid", &(TOP.m_axi_bvalid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_rdata", &(TOP.m_axi_rdata), false, VLVT_UINT32, VLVD_IN|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("m_axi_rid", &(TOP.m_axi_rid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("m_axi_rlast", &(TOP.m_axi_rlast), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_rready", &(TOP.m_axi_rready), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_rresp", &(TOP.m_axi_rresp), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_TOP->varInsert("m_axi_rvalid", &(TOP.m_axi_rvalid), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_wdata", &(TOP.m_axi_wdata), false, VLVT_UINT32, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_TOP->varInsert("m_axi_wlast", &(TOP.m_axi_wlast), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_wready", &(TOP.m_axi_wready), false, VLVT_UINT8, VLVD_IN|VLVF_PUB_RW, 0, 0);
    __Vscopep_TOP->varInsert("m_axi_wstrb", &(TOP.m_axi_wstrb), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_TOP->varInsert("m_axi_wvalid", &(TOP.m_axi_wvalid), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_TOP->varInsert("rst_n", &(TOP.rst_n), false, VLVT_UINT8, VLVD_OUT|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("aclk", &(TOP.cpu_test_harness__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("aresetn", &(TOP.cpu_test_harness__DOT__aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("bvalid_reg", &(TOP.cpu_test_harness__DOT__bvalid_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("clk", &(TOP.cpu_test_harness__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("instruction", &(TOP.cpu_test_harness__DOT__instruction), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_araddr", &(TOP.cpu_test_harness__DOT__m_axi_araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arburst", &(TOP.cpu_test_harness__DOT__m_axi_arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arid", &(TOP.cpu_test_harness__DOT__m_axi_arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arlen", &(TOP.cpu_test_harness__DOT__m_axi_arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arready", &(TOP.cpu_test_harness__DOT__m_axi_arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arsize", &(TOP.cpu_test_harness__DOT__m_axi_arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_arvalid", &(TOP.cpu_test_harness__DOT__m_axi_arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awaddr", &(TOP.cpu_test_harness__DOT__m_axi_awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awburst", &(TOP.cpu_test_harness__DOT__m_axi_awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awid", &(TOP.cpu_test_harness__DOT__m_axi_awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awlen", &(TOP.cpu_test_harness__DOT__m_axi_awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awready", &(TOP.cpu_test_harness__DOT__m_axi_awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awsize", &(TOP.cpu_test_harness__DOT__m_axi_awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_awvalid", &(TOP.cpu_test_harness__DOT__m_axi_awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_bid", &(TOP.cpu_test_harness__DOT__m_axi_bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_bready", &(TOP.cpu_test_harness__DOT__m_axi_bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_bresp", &(TOP.cpu_test_harness__DOT__m_axi_bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_bvalid", &(TOP.cpu_test_harness__DOT__m_axi_bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rdata", &(TOP.cpu_test_harness__DOT__m_axi_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rid", &(TOP.cpu_test_harness__DOT__m_axi_rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rlast", &(TOP.cpu_test_harness__DOT__m_axi_rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rready", &(TOP.cpu_test_harness__DOT__m_axi_rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rresp", &(TOP.cpu_test_harness__DOT__m_axi_rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_rvalid", &(TOP.cpu_test_harness__DOT__m_axi_rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_wdata", &(TOP.cpu_test_harness__DOT__m_axi_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_wlast", &(TOP.cpu_test_harness__DOT__m_axi_wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_wready", &(TOP.cpu_test_harness__DOT__m_axi_wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_wstrb", &(TOP.cpu_test_harness__DOT__m_axi_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness->varInsert("m_axi_wvalid", &(TOP.cpu_test_harness__DOT__m_axi_wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("pc", &(TOP.cpu_test_harness__DOT__pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("ram", &(TOP.cpu_test_harness__DOT__ram), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,2047 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("read_active", &(TOP.cpu_test_harness__DOT__read_active), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("read_addr", &(TOP.cpu_test_harness__DOT__read_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("read_count", &(TOP.cpu_test_harness__DOT__read_count), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness->varInsert("read_length", &(TOP.cpu_test_harness__DOT__read_length), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness->varInsert("rst_n", &(TOP.cpu_test_harness__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("write_active", &(TOP.cpu_test_harness__DOT__write_active), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness->varInsert("write_addr", &(TOP.cpu_test_harness__DOT__write_addr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness->varInsert("write_count", &(TOP.cpu_test_harness__DOT__write_count), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_control", &(TOP.cpu_test_harness__DOT__core__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_last_bit", &(TOP.cpu_test_harness__DOT__core__DOT__alu_last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_result", &(TOP.cpu_test_harness__DOT__core__DOT__alu_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_source", &(TOP.cpu_test_harness__DOT__core__DOT__alu_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_src2", &(TOP.cpu_test_harness__DOT__core__DOT__alu_src2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_unsigned_less", &(TOP.cpu_test_harness__DOT__core__DOT__alu_unsigned_less), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("alu_zero", &(TOP.cpu_test_harness__DOT__core__DOT__alu_zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("clk", &(TOP.cpu_test_harness__DOT__core__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("control_trap_valid", &(TOP.cpu_test_harness__DOT__core__DOT__control_trap_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("d_cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__d_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("d_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__d_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("data", &(TOP.cpu_test_harness__DOT__core__DOT__data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("data_cache_flush_done", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache_flush_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("data_next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__data_next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("data_read_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("data_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__data_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("data_write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_d_cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__debug_d_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_d_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__debug_d_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_d_next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__debug_d_next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_d_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__debug_d_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_i_cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__debug_i_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_i_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__debug_i_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_i_next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__debug_i_next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_i_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__debug_i_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_instruction", &(TOP.cpu_test_harness__DOT__core__DOT__debug_instruction), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_pc", &(TOP.cpu_test_harness__DOT__core__DOT__debug_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("debug_pc_next", &(TOP.cpu_test_harness__DOT__core__DOT__debug_pc_next), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("dest_reg", &(TOP.cpu_test_harness__DOT__core__DOT__dest_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("f3", &(TOP.cpu_test_harness__DOT__core__DOT__f3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core->varInsert("fence", &(TOP.cpu_test_harness__DOT__core__DOT__fence), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("fence_i", &(TOP.cpu_test_harness__DOT__core__DOT__fence_i), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("fence_i_request", &(TOP.cpu_test_harness__DOT__core__DOT__fence_i_request), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("func7", &(TOP.cpu_test_harness__DOT__core__DOT__func7), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("i_cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__i_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("i_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__i_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("imm_source", &(TOP.cpu_test_harness__DOT__core__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core->varInsert("immediate", &(TOP.cpu_test_harness__DOT__core__DOT__immediate), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("instr_cache_invalidate_done", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache_invalidate_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("instr_next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__instr_next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("instr_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__instr_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("instruction", &(TOP.cpu_test_harness__DOT__core__DOT__instruction), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("last_bit", &(TOP.cpu_test_harness__DOT__core__DOT__last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_byte_enable", &(TOP.cpu_test_harness__DOT__core__DOT__mem_byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_read", &(TOP.cpu_test_harness__DOT__core__DOT__mem_read), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_read_enable", &(TOP.cpu_test_harness__DOT__core__DOT__mem_read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_read_write_back_data", &(TOP.cpu_test_harness__DOT__core__DOT__mem_read_write_back_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_read_write_back_valid", &(TOP.cpu_test_harness__DOT__core__DOT__mem_read_write_back_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_write", &(TOP.cpu_test_harness__DOT__core__DOT__mem_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("mem_write_data", &(TOP.cpu_test_harness__DOT__core__DOT__mem_write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("op", &(TOP.cpu_test_harness__DOT__core__DOT__op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core->varInsert("pc", &(TOP.cpu_test_harness__DOT__core__DOT__pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("pc_next", &(TOP.cpu_test_harness__DOT__core__DOT__pc_next), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("pc_plus_four", &(TOP.cpu_test_harness__DOT__core__DOT__pc_plus_four), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("pc_plus_second_add", &(TOP.cpu_test_harness__DOT__core__DOT__pc_plus_second_add), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("pc_source", &(TOP.cpu_test_harness__DOT__core__DOT__pc_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("raw_imm", &(TOP.cpu_test_harness__DOT__core__DOT__raw_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,24,0);
    __Vscopep_cpu_test_harness__core->varInsert("read_reg1", &(TOP.cpu_test_harness__DOT__core__DOT__read_reg1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("read_reg2", &(TOP.cpu_test_harness__DOT__core__DOT__read_reg2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("reg_write", &(TOP.cpu_test_harness__DOT__core__DOT__reg_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("rst_n", &(TOP.cpu_test_harness__DOT__core__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("second_add_source", &(TOP.cpu_test_harness__DOT__core__DOT__second_add_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core->varInsert("shamt", &(TOP.cpu_test_harness__DOT__core__DOT__shamt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("shift_amount", &(TOP.cpu_test_harness__DOT__core__DOT__shift_amount), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("source_reg1", &(TOP.cpu_test_harness__DOT__core__DOT__source_reg1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("source_reg2", &(TOP.cpu_test_harness__DOT__core__DOT__source_reg2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("system_imm", &(TOP.cpu_test_harness__DOT__core__DOT__system_imm), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,11,0);
    __Vscopep_cpu_test_harness__core->varInsert("trap_cause", &(TOP.cpu_test_harness__DOT__core__DOT__trap_cause), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core->varInsert("trap_pc", &(TOP.cpu_test_harness__DOT__core__DOT__trap_pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("trap_valid", &(TOP.cpu_test_harness__DOT__core__DOT__trap_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("unsigned_less", &(TOP.cpu_test_harness__DOT__core__DOT__unsigned_less), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("wb_valid", &(TOP.cpu_test_harness__DOT__core__DOT__wb_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core->varInsert("write_back_data", &(TOP.cpu_test_harness__DOT__core__DOT__write_back_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core->varInsert("write_back_source", &(TOP.cpu_test_harness__DOT__core__DOT__write_back_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("alu_control", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("alu_result", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__alu_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("last_bit", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("shamt", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__shamt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("src1", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__src1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("src2", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__src2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("unsigned_less", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__unsigned_less), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__alu_inst->varInsert("zero", &(TOP.cpu_test_harness__DOT__core__DOT__alu_inst__DOT__zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__arbitrer->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.cpu_test_harness__DOT__core__DOT__arbitrer__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__arbitrer->varInsert("d_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__arbitrer__DOT__d_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__arbitrer->varInsert("i_cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__arbitrer__DOT__i_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_control", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_last_bit", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_op", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_source", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_unsigned_less", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_unsigned_less), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("alu_zero", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__alu_zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("assert_branch", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__assert_branch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("branch", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__branch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("fence", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__fence), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("fence_i", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__fence_i), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("func3", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__func3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("func7", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__func7), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("imm_source", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("jump", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__jump), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("mem_read", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__mem_read), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("mem_write", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__mem_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("op", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("pc_source", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__pc_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("reg_write", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__reg_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("second_add_source", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__second_add_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("shamt", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__shamt), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("system_imm", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__system_imm), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("trap_cause", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__trap_cause), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__control->varInsert("trap_valid", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__trap_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__control->varInsert("write_back_source", &(TOP.cpu_test_harness__DOT__core__DOT__control__DOT__write_back_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("aclk", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("actual_write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__actual_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("address", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__address), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("byte_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("byte_enable_mask", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable_mask), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_block_tag", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_data", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_data), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 2 ,127,0 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_dirty", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("cache_valid", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("clk", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("comb_stall", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__comb_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("flush", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("flush_done", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("flush_pending", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush_pending), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("hit", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("invalidate", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__invalidate), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("invalidate_done", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__invalidate_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("next_cache_dirty", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("next_cache_valid", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("next_set_ptr_out", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_set_ptr_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("next_state", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("read_data", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("read_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("req_block_tag", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__req_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,9);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("req_index", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__req_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,8,2);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("rst_n", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("seq_stall", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__seq_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("set_ptr_out", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__set_ptr_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("state", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("write_data", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__data_cache->varInsert("write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__data_cache__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("aclk", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("actual_write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__actual_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("address", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__address), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("byte_enable", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("byte_enable_mask", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable_mask), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_block_tag", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_data", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_data), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 2 ,127,0 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_dirty", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_stall", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_state", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("cache_valid", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("clk", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("comb_stall", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__comb_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("flush", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("flush_done", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("flush_pending", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush_pending), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("hit", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("invalidate", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__invalidate), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("invalidate_done", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__invalidate_done), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("next_cache_dirty", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("next_cache_valid", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("next_set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("next_set_ptr_out", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_set_ptr_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("next_state", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("read_data", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("read_enable", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("req_block_tag", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__req_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,31,9);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("req_index", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__req_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,8,2);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("rst_n", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("seq_stall", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__seq_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("set_ptr", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("set_ptr_out", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__set_ptr_out), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,6,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("state", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("write_data", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__instr_cache->varInsert("write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__instr_cache__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("alu_result_address", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__alu_result_address), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("byte_enable", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("data", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("f3", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__f3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("offset", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__offset), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__ls_decoder->varInsert("reg_read", &(TOP.cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__reg_read), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("aclk", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("araddr", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arburst", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("aresetn", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arlen", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arlock", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arqos", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arsize", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("arvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awaddr", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awburst", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awlen", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awlock", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awqos", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awsize", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("awvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("bid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("bready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("bresp", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("bvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rdata", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rlast", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rresp", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("rvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("wdata", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("wlast", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("wready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("wstrb", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_data->varInsert("wvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("aclk", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("araddr", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arburst", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("aresetn", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arlen", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arlock", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arqos", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arsize", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("arvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awaddr", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awburst", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awlen", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awlock", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awqos", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awsize", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("awvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("bid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("bready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("bresp", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("bvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rdata", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rlast", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rresp", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("rvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("wdata", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("wlast", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("wready", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("wstrb", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__m_axi_inst->varInsert("wvalid", &(TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("be_mask", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__be_mask), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("f3", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__f3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("masked_data", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__masked_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("mem_data", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__mem_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("raw_data", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__raw_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("sign_extend", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__sign_extend), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("valid", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__reader_inst->varInsert("wb_data", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__wb_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1->varInsert("i", &(TOP.cpu_test_harness__DOT__core__DOT__reader_inst__DOT__mask_apply__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("address1", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__address1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("address2", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__address2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("address3", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__address3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("clk", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("read_data1", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__read_data1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("read_data2", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__read_data2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("registers", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__registers), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,31 ,31,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("rst_n", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("write_data", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__regfile->varInsert("write_enable", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__core__regfile__unnamedblk1->varInsert("i", &(TOP.cpu_test_harness__DOT__core__DOT__regfile__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__sign_extender->varInsert("imm_source", &(TOP.cpu_test_harness__DOT__core__DOT__sign_extender__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__core__sign_extender->varInsert("immediate", &(TOP.cpu_test_harness__DOT__core__DOT__sign_extender__DOT__immediate), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__core__sign_extender->varInsert("raw_src", &(TOP.cpu_test_harness__DOT__core__DOT__sign_extender__DOT__raw_src), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,24,0);
    __Vscopep_cpu_test_harness__data_memory->varInsert("mem", &(TOP.cpu_test_harness__DOT__data_memory__DOT__mem), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 1, 1 ,0,127 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__m_axi.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__m_axi.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__cpu_test_harness__DOT__m_axi.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("aclk", &(TOP__cpu_test_harness__DOT__m_axi.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("araddr", &(TOP__cpu_test_harness__DOT__m_axi.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arburst", &(TOP__cpu_test_harness__DOT__m_axi.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("aresetn", &(TOP__cpu_test_harness__DOT__m_axi.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arid", &(TOP__cpu_test_harness__DOT__m_axi.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arlen", &(TOP__cpu_test_harness__DOT__m_axi.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arlock", &(TOP__cpu_test_harness__DOT__m_axi.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arqos", &(TOP__cpu_test_harness__DOT__m_axi.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arready", &(TOP__cpu_test_harness__DOT__m_axi.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arsize", &(TOP__cpu_test_harness__DOT__m_axi.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("arvalid", &(TOP__cpu_test_harness__DOT__m_axi.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awaddr", &(TOP__cpu_test_harness__DOT__m_axi.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awburst", &(TOP__cpu_test_harness__DOT__m_axi.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awid", &(TOP__cpu_test_harness__DOT__m_axi.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awlen", &(TOP__cpu_test_harness__DOT__m_axi.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,7,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awlock", &(TOP__cpu_test_harness__DOT__m_axi.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awqos", &(TOP__cpu_test_harness__DOT__m_axi.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awready", &(TOP__cpu_test_harness__DOT__m_axi.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awsize", &(TOP__cpu_test_harness__DOT__m_axi.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,2,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("awvalid", &(TOP__cpu_test_harness__DOT__m_axi.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("bid", &(TOP__cpu_test_harness__DOT__m_axi.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("bready", &(TOP__cpu_test_harness__DOT__m_axi.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("bresp", &(TOP__cpu_test_harness__DOT__m_axi.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("bvalid", &(TOP__cpu_test_harness__DOT__m_axi.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rdata", &(TOP__cpu_test_harness__DOT__m_axi.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rid", &(TOP__cpu_test_harness__DOT__m_axi.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rlast", &(TOP__cpu_test_harness__DOT__m_axi.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rready", &(TOP__cpu_test_harness__DOT__m_axi.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rresp", &(TOP__cpu_test_harness__DOT__m_axi.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("rvalid", &(TOP__cpu_test_harness__DOT__m_axi.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("wdata", &(TOP__cpu_test_harness__DOT__m_axi.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("wlast", &(TOP__cpu_test_harness__DOT__m_axi.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("wready", &(TOP__cpu_test_harness__DOT__m_axi.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("wstrb", &(TOP__cpu_test_harness__DOT__m_axi.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 0, 1 ,3,0);
    __Vscopep_cpu_test_harness__m_axi->varInsert("wvalid", &(TOP__cpu_test_harness__DOT__m_axi.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_cpu_test_harness__regfile->varInsert("registers", &(TOP.cpu_test_harness__DOT__regfile__DOT__registers), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_CONTINUOUSLY, 1, 1 ,0,31 ,31,0);
    __Vscopep_cpu_test_harness__unnamedblk1->varInsert("preload_index", &(TOP.cpu_test_harness__DOT__unnamedblk1__DOT__preload_index), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_instruction_set_pkg->varInsert("DataCount", const_cast<void*>(static_cast<const void*>(&(TOP__instruction_set_pkg.DataCount))), true, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_cpu_test_harness);
    __Vhier.remove(0, __Vscopep_instruction_set_pkg);
    __Vhier.remove(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__core);
    __Vhier.remove(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__data_memory);
    __Vhier.remove(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__m_axi);
    __Vhier.remove(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__regfile);
    __Vhier.remove(__Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness__unnamedblk1);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__alu_inst);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__arbitrer);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__control);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__data_cache);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__instr_cache);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__ls_decoder);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__m_axi_data);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__m_axi_inst);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__reader_inst);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__regfile);
    __Vhier.remove(__Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core__sign_extender);
    __Vhier.remove(__Vscopep_cpu_test_harness__core__reader_inst, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply);
    __Vhier.remove(__Vscopep_cpu_test_harness__core__reader_inst__mask_apply, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1);
    __Vhier.remove(__Vscopep_cpu_test_harness__core__regfile, __Vscopep_cpu_test_harness__core__regfile__unnamedblk1);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_TOP, __Vscopep_TOP = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness, __Vscopep_cpu_test_harness = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core, __Vscopep_cpu_test_harness__core = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__alu_inst, __Vscopep_cpu_test_harness__core__alu_inst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__arbitrer, __Vscopep_cpu_test_harness__core__arbitrer = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__control, __Vscopep_cpu_test_harness__core__control = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__data_cache, __Vscopep_cpu_test_harness__core__data_cache = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__instr_cache, __Vscopep_cpu_test_harness__core__instr_cache = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__ls_decoder, __Vscopep_cpu_test_harness__core__ls_decoder = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__m_axi_data, __Vscopep_cpu_test_harness__core__m_axi_data = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__m_axi_inst, __Vscopep_cpu_test_harness__core__m_axi_inst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__reader_inst, __Vscopep_cpu_test_harness__core__reader_inst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__reader_inst__mask_apply, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1, __Vscopep_cpu_test_harness__core__reader_inst__mask_apply__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__regfile, __Vscopep_cpu_test_harness__core__regfile = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__regfile__unnamedblk1, __Vscopep_cpu_test_harness__core__regfile__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__core__sign_extender, __Vscopep_cpu_test_harness__core__sign_extender = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__data_memory, __Vscopep_cpu_test_harness__data_memory = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__m_axi, __Vscopep_cpu_test_harness__m_axi = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__regfile, __Vscopep_cpu_test_harness__regfile = nullptr);
    VL_DO_CLEAR(delete __Vscopep_cpu_test_harness__unnamedblk1, __Vscopep_cpu_test_harness__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_instruction_set_pkg, __Vscopep_instruction_set_pkg = nullptr);
    // Tear down sub module instances
    TOP__instruction_set_pkg.dtor();
    TOP__cpu_test_harness__DOT__m_axi.dtor();
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_inst.dtor();
    TOP__cpu_test_harness__DOT__core__DOT__m_axi_data.dtor();
}
