// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtop_axi_if;
class Vtop_instruction_set_pkg;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_instruction_set_pkg* __PVT__instruction_set_pkg;
    Vtop_axi_if* __PVT__cpu_test_harness__DOT__m_axi;
    Vtop_axi_if* __PVT__cpu_test_harness__DOT__core__DOT__m_axi_data;
    Vtop_axi_if* __PVT__cpu_test_harness__DOT__core__DOT__m_axi_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_OUT8(clk,0,0);
        VL_OUT8(rst_n,0,0);
        VL_OUT8(aclk,0,0);
        VL_OUT8(aresetn,0,0);
        VL_OUT8(m_axi_awid,3,0);
        VL_OUT8(m_axi_awlen,7,0);
        VL_OUT8(m_axi_awsize,2,0);
        VL_OUT8(m_axi_awburst,1,0);
        VL_OUT8(m_axi_awvalid,0,0);
        VL_IN8(m_axi_awready,0,0);
        VL_OUT8(m_axi_wstrb,3,0);
        VL_OUT8(m_axi_wlast,0,0);
        VL_OUT8(m_axi_wvalid,0,0);
        VL_IN8(m_axi_wready,0,0);
        VL_IN8(m_axi_bid,3,0);
        VL_IN8(m_axi_bresp,1,0);
        VL_IN8(m_axi_bvalid,0,0);
        VL_OUT8(m_axi_bready,0,0);
        VL_OUT8(m_axi_arid,3,0);
        VL_OUT8(m_axi_arlen,7,0);
        VL_OUT8(m_axi_arsize,2,0);
        VL_OUT8(m_axi_arburst,1,0);
        VL_OUT8(m_axi_arvalid,0,0);
        VL_IN8(m_axi_arready,0,0);
        VL_IN8(m_axi_rid,3,0);
        VL_IN8(m_axi_rresp,1,0);
        VL_IN8(m_axi_rlast,0,0);
        VL_IN8(m_axi_rvalid,0,0);
        VL_OUT8(m_axi_rready,0,0);
        CData/*0:0*/ cpu_test_harness__DOT__clk;
        CData/*0:0*/ cpu_test_harness__DOT__rst_n;
        CData/*0:0*/ cpu_test_harness__DOT__aclk;
        CData/*0:0*/ cpu_test_harness__DOT__aresetn;
        CData/*3:0*/ cpu_test_harness__DOT__m_axi_awid;
        CData/*7:0*/ cpu_test_harness__DOT__m_axi_awlen;
        CData/*2:0*/ cpu_test_harness__DOT__m_axi_awsize;
        CData/*1:0*/ cpu_test_harness__DOT__m_axi_awburst;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_awvalid;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_awready;
        CData/*3:0*/ cpu_test_harness__DOT__m_axi_wstrb;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_wlast;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_wvalid;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_wready;
        CData/*3:0*/ cpu_test_harness__DOT__m_axi_bid;
        CData/*1:0*/ cpu_test_harness__DOT__m_axi_bresp;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_bvalid;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_bready;
        CData/*3:0*/ cpu_test_harness__DOT__m_axi_arid;
        CData/*7:0*/ cpu_test_harness__DOT__m_axi_arlen;
        CData/*2:0*/ cpu_test_harness__DOT__m_axi_arsize;
        CData/*1:0*/ cpu_test_harness__DOT__m_axi_arburst;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_arvalid;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_arready;
        CData/*3:0*/ cpu_test_harness__DOT__m_axi_rid;
        CData/*1:0*/ cpu_test_harness__DOT__m_axi_rresp;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_rlast;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_rvalid;
        CData/*0:0*/ cpu_test_harness__DOT__m_axi_rready;
        CData/*0:0*/ cpu_test_harness__DOT__read_active;
        CData/*7:0*/ cpu_test_harness__DOT__read_count;
        CData/*7:0*/ cpu_test_harness__DOT__read_length;
        CData/*0:0*/ cpu_test_harness__DOT__write_active;
        CData/*7:0*/ cpu_test_harness__DOT__write_count;
        CData/*0:0*/ cpu_test_harness__DOT__bvalid_reg;
    };
    struct {
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__clk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__rst_n;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__debug_i_cache_state;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__debug_d_cache_state;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__debug_i_set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__debug_i_next_set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__debug_d_set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__debug_d_next_set_ptr;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__debug_i_cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__debug_d_cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__trap_valid;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__trap_cause;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__i_cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__d_cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache_flush_done;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache_invalidate_done;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_next_set_ptr;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__mem_byte_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__mem_read_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__mem_write;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_read_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_write_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control_trap_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__fence_i_request;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__i_cache_state;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__d_cache_state;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_next_set_ptr;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__pc_source;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__second_add_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_zero;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__alu_control;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__imm_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__reg_write;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_source;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__write_back_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__fence;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__fence_i;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__func7;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__shamt;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__op;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__f3;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_last_bit;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_unsigned_less;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__source_reg1;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__source_reg2;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__dest_reg;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__wb_valid;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__shift_amount;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__last_bit;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__unsigned_less;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__mem_read_write_back_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__clk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__rst_n;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__aclk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__read_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__write_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__invalidate;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush_done;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__invalidate_done;
    };
    struct {
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_state;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__set_ptr_out;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_set_ptr_out;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__actual_write_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__comb_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__seq_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_cache_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_dirty;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_cache_dirty;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__req_index;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_set_ptr;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__hit;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__state;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__next_state;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__flush_pending;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__clk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__rst_n;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__aclk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__read_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__write_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__invalidate;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush_done;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__invalidate_done;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_state;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__set_ptr_out;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_set_ptr_out;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__actual_write_enable;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__comb_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__seq_stall;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_cache_valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_dirty;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_cache_dirty;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__req_index;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__set_ptr;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_set_ptr;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__hit;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__state;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__next_state;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__flush_pending;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__arbitrer__DOT__i_cache_state;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__arbitrer__DOT__d_cache_state;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__op;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__func3;
        CData/*6:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__func7;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_zero;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__shamt;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_last_bit;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_unsigned_less;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_control;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__imm_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__reg_write;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__mem_write;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_source;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__write_back_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__pc_source;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__second_add_source;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__mem_read;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__fence;
    };
    struct {
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__fence_i;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__trap_valid;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__trap_cause;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__alu_op;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__branch;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__jump;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__assert_branch;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__clk;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__rst_n;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__address1;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__address2;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__write_enable;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__address3;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__sign_extender__DOT__imm_source;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__alu_control;
        CData/*4:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__shamt;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__zero;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__last_bit;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__unsigned_less;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__f3;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__byte_enable;
        CData/*1:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__offset;
        CData/*3:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__be_mask;
        CData/*2:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__f3;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__valid;
        CData/*0:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__sign_extend;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cpu_test_harness__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cpu_test_harness__DOT__core__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cpu_test_harness__DOT__core__DOT__instr_cache__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cpu_test_harness__DOT__core__DOT__data_cache__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__cpu_test_harness__DOT__core__DOT__regfile__DOT__clk__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*11:0*/ cpu_test_harness__DOT__core__DOT__system_imm;
        SData/*11:0*/ cpu_test_harness__DOT__core__DOT__control__DOT__system_imm;
        VL_OUT(m_axi_awaddr,31,0);
        VL_OUT(m_axi_wdata,31,0);
        VL_OUT(m_axi_araddr,31,0);
        VL_IN(m_axi_rdata,31,0);
        IData/*31:0*/ cpu_test_harness__DOT__m_axi_awaddr;
        IData/*31:0*/ cpu_test_harness__DOT__m_axi_wdata;
        IData/*31:0*/ cpu_test_harness__DOT__m_axi_araddr;
        IData/*31:0*/ cpu_test_harness__DOT__m_axi_rdata;
        IData/*31:0*/ cpu_test_harness__DOT__pc;
        IData/*31:0*/ cpu_test_harness__DOT__instruction;
        IData/*31:0*/ cpu_test_harness__DOT__read_addr;
        IData/*31:0*/ cpu_test_harness__DOT__write_addr;
        IData/*31:0*/ cpu_test_harness__DOT__unnamedblk1__DOT__preload_index;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__debug_pc;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__debug_pc_next;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__debug_instruction;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__trap_pc;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__pc;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instruction;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__mem_read;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__alu_result;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__mem_write_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__pc_next;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__pc_plus_second_add;
    };
    struct {
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__pc_plus_four;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__immediate;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__read_reg1;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__read_reg2;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__write_back_data;
        IData/*24:0*/ cpu_test_harness__DOT__core__DOT__raw_imm;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__alu_src2;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__mem_read_write_back_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__address;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__write_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__read_data;
        VlWide<128>/*4095:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_data;
        IData/*22:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__cache_block_tag;
        IData/*22:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__req_block_tag;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable_mask;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__address;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__write_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__read_data;
        VlWide<128>/*4095:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_data;
        IData/*22:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__cache_block_tag;
        IData/*22:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__req_block_tag;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable_mask;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__read_data1;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__read_data2;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__write_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__regfile__DOT__unnamedblk1__DOT__i;
        IData/*24:0*/ cpu_test_harness__DOT__core__DOT__sign_extender__DOT__raw_src;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__sign_extender__DOT__immediate;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__src1;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__src2;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__alu_inst__DOT__alu_result;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__alu_result_address;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__reg_read;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__ls_decoder__DOT__data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__mem_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__wb_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__masked_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__raw_data;
        IData/*31:0*/ cpu_test_harness__DOT__core__DOT__reader_inst__DOT__mask_apply__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        VlUnpacked<IData/*31:0*/, 2048> cpu_test_harness__DOT__ram;
        VlUnpacked<IData/*31:0*/, 32> cpu_test_harness__DOT__regfile__DOT__registers;
        VlUnpacked<IData/*31:0*/, 128> cpu_test_harness__DOT__data_memory__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> cpu_test_harness__DOT__core__DOT__regfile__DOT__registers;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 32>, false, IData/*31:0*/, 1> __VdlyCommitQueuecpu_test_harness__DOT__core__DOT__regfile__DOT__registers;
    VlDelayScheduler __VdlySched;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr IData/*31:0*/ cpu_test_harness__DOT__core__DOT__instr_cache__DOT__CACHE_SIZE = 0x00000080U;
    static constexpr IData/*31:0*/ cpu_test_harness__DOT__core__DOT__data_cache__DOT__CACHE_SIZE = 0x00000080U;
    static constexpr IData/*31:0*/ cpu_test_harness__DOT__core__DOT__arbitrer__DOT__CACHE_SIZE = 0x00000080U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
