# first design some function help convert hex to bin , another cocotb.test to handle the cpu reset
import cocotb
from cocotb.triggers import Timer, RisingEdge
from cocotb.clock import Clock
import random
import numpy

AXI_PERIOD = 10
CPU_PERIOD = 10

def binary_to_hex(bin_str):
    # Convert binary string to hexadecimal
    hex_str = hex(int(str(bin_str), 2))[2:]
    hex_str = hex_str.zfill(8)
    return hex_str.upper()

def hex_to_bin(hex_str):
    # Convert hex str to bin
    bin_str = bin(int(str(hex_str), 16))[2:]
    bin_str = bin_str.zfill(32)
    return bin_str.upper()

def read_cache(cache_data, line):
    # cache_data is a packed [127:0][31:0] array; word 0 occupies the
    # most-significant 32 bits in cocotb's flattened representation.
    upper = 32 * (129 - line) - 1
    lower = 32 * (128 - line)
    return int(cache_data.value[lower:upper])

async def inst_clocks(dut):
    # The wrapper owns the clock.  Give its initial block time to start.
    await Timer(1, units="ns")

async def cpu_reset(dut):
    # Reset is generated by cpu_harness so Verilator owns the top-level
    # reset nets.  Wait until the synchronous CPU reset has been released.
    await Timer(25, units="ns")
    assert int(dut.rst_n.value) == 1, "CPU reset did not de-assert"



#formal test writing here below 
#@ cocotb.test()
#async def cpu_init_test(dut):
    #cocotb.start_soon(Clock(dut.clk, 1, units = "ns").start())
    #await RisingEdge(dut.clk)

    #await cpu_reset(dut)
    #assert binary_to_hex(dut.pc.value)=="00000000"
    # Load the expected instruction memory as binary
    # Note that this is loaded in sim directly via the verilog code
    # This load is only for expected
    #imem = []
    #with open ("test_imemory.hex", "r") as file:
    #    for line in file:
    #        line_content = line.split("//")[0].strip()
    #        if line_content:
    #            imem.append(hex_to_bin(line_content))

    #for counter in range(len(imem)):
    #    expected_instruction = imem[counter]
    #    assert dut.instruction.value == expected_instruction
    #    await RisingEdge(dut.clk)

@cocotb.test()
async def cpu_insrt_test(dut):
    """Runs a lw datapath test"""
    await cpu_reset(dut)

    
    ##################
    # SAVE BASE ADDR IN X3
    # 00000193  //DATA ADDR STORE                         | x3  <= 00001000
    ##################
    print("\n\nSAVING DATA BASE ADDR\n\n")

    # Wait a clock cycle for the instruction to execute
    for _ in range(1000):
        if int(dut.core.stall.value) == 0:
            break
        await RisingEdge(dut.clk)
    else:
        raise RuntimeError(
            "Initial instruction-cache fill did not complete: "
            f"state={dut.core.i_cache_state.value}, "
            f"arvalid={dut.m_axi_arvalid.value}, "
            f"arready={dut.m_axi_arready.value}, "
            f"rvalid={dut.m_axi_rvalid.value}"
        )

    await RisingEdge(dut.clk) # lui x3 0x1
    # Check the value of reg x18
    assert binary_to_hex(dut.core.regfile.registers[3].value) == "00001000"
    ##################
    # LOAD WORD TEST 
    # lw x18 0x8(x0)
    ##################
    print("\n\nTESTING LW\n\n")

    # The first instruction for the test in imem.hex load the data from
    # dmem @ adress 0x00000008 that happens to be 0xDEADBEEF into register x18

    # Wait a clock cycle for the instruction to execute
    await RisingEdge(dut.clk)

    # Check the value of reg x18
    assert binary_to_hex(dut.regfile.registers[18].value) == "DEADBEEF"

    ##################
    # STORE WORD TEST 
    # sw x18 0xC(x0)
    ##################
    print("\n\nTESTING SW\n\n")
    test_address = int(0xC / 4) #mem is byte adressed but is made out of words in the eyes of the software
    # The second instruction for the test in imem.hex stores the data from
    # x18 (that happens to be 0xDEADBEEF from the previous LW test) @ adress 0x0000000C 

    await RisingEdge(dut.clk) # sw x18 0xC(x3)
    # r type command testing 
    expected_result = (0xDEADBEEF + 0x00000AAA) & 0xFFFFFFFF
    await RisingEdge(dut.clk) # lw x19 0x10(x0)
    assert binary_to_hex(dut.regfile.registers[19].value) == "00000AAA"
    await RisingEdge(dut.clk) # add x20 x18 x19
    assert binary_to_hex(dut.regfile.registers[20].value) == hex(expected_result)[2:].upper()
    # Use last expected result, as this instr uses last op result register
    expected_result = expected_result & 0xDEADBEEF
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[21].value) == "DEAD8889"

    print("\n\nTESTING OR\n\n")
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[5].value) == "125F552D"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[6].value) == "7F4FD46A"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[7].value) == "7F5FD56F"

# ...

    ##################
    # BEQ TEST
    # 00730663  //BEQ TEST START :    beq x6 x7 0xC       | #1 SHOULD NOT BRANCH
    # 00802B03  //                    lw x22 0x8(x0)      | x22 <= DEADBEEF
    # 01690863  //                    beq x18 x22 0x10    | #2 SHOULD BRANCH (+ offset)
    # 00000013  //                    nop                 | NEVER EXECUTED
    # 00000013  //                    nop                 | NEVER EXECUTED
    # 00000663  //                    beq x0 x0 0xC       | #4 SHOULD BRANCH (avoid loop)
    # 00002B03  //                    lw x22 0x0(x0)      | x22 <= AEAEAEAE
    # FF6B0CE3  //                    beq x22 x22 -0x8    | #3 SHOULD BRANCH (-offset)
    # 00000013  //                    nop                 | FINAL NOP
    ##################

    print("\n\nTESTING BEQ\n\n")
    assert binary_to_hex(dut.instruction.value) == "0081AB03"

    await RisingEdge(dut.clk) # beq x6 x7 0xC NOT TAKEN
    # Check if the current instruction is the one we expected
    # The previous rising edge executes the load at PC=0x28, so fetch now
    # points at the following BEQ (PC=0x2c).
    assert binary_to_hex(dut.instruction.value) == "01690863"

    await RisingEdge(dut.clk) # lw x22 0x8(x0)
    assert binary_to_hex(dut.regfile.registers[22].value) == "DEADBEEF"

    await RisingEdge(dut.clk) # beq x18 x22 0x10 TAKEN
    # Check if the current instruction is the one we expected
    assert binary_to_hex(dut.instruction.value) == "FF6B0CE3"

    await RisingEdge(dut.clk) # lw x22 0x0(x0)
    assert binary_to_hex(dut.regfile.registers[22].value) == "AEAEAEAE"

    await RisingEdge(dut.clk) # beq x22 x22 -0x8 TAKEN
    # Check if the current instruction is the one we expected
    assert binary_to_hex(dut.instruction.value) == "00000013"

    await RisingEdge(dut.clk) # beq x0 x0 0xC TAKEN
    # Check if the current instruction is the one we expected
    assert binary_to_hex(dut.instruction.value) == "00C000EF"



    # ...

    ##################
    # 00C000EF  //JAL TEST START :    jal x1 0xC          | #1 jump @PC+0xC | PC 0x44
    # 00000013  //                    nop                 | NEVER EXECUTED  | PC 0x48
    # 00C000EF  //                    jal x1 0xC          | #2 jump @PC-0x4 | PC 0x4C   
    # FFDFF0EF  //                    jal x1 -4           | #2 jump @PC-0x4 | PC 0x50
    # 00000013  //                    nop                 | NEVER EXECUTED  | PC 0x54
    # 00C02383  //                    lw x7 0xC(x0)       | x7 <= DEADBEEF  | PC 0x58
    ##################
    print("\n\nTESTING JAL\n\n")
    # Execute the final branch-test NOP.  The first JAL is at PC=0x48 in
    # test_imemory.hex (the older test image placed it at 0x44).
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.instruction.value) == "FFDFF0EF"
    assert binary_to_hex(dut.pc.value) == "00000054"
    assert binary_to_hex(dut.regfile.registers[1].value) == "0000004C"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.instruction.value) == "00C000EF"
    assert binary_to_hex(dut.pc.value) == "00000050"
    assert binary_to_hex(dut.regfile.registers[1].value) == "00000058"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.instruction.value) == "00C1A383"
    assert binary_to_hex(dut.pc.value) == "0000005C"
    assert binary_to_hex(dut.regfile.registers[1].value) == "00000054"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[7].value) == "DEADBEEF"



    #addi test
    # 1AB38D13  //                    addi x26 x7 0x1AB   | x26 <= DEADC09A
    # F2130C93  //                    addi x25 x6 0xF21   | x25 <= DEADBE10
    print("\n\nTESTING ADDI\n\n")
    assert binary_to_hex(dut.instruction.value) == "1AB38D13"    
    assert not binary_to_hex(dut.regfile.registers[26].value) == "DEADC09A"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.instruction.value) == "F2130C93"
    assert binary_to_hex(dut.regfile.registers[26].value) == "DEADC09A"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[25].value) == "7F4FD38B"

    ##################
    # AUIPC TEST (PC befor is 0x64)
    # 1F1FA297  //AUIPC TEST START :  auipc x5 0x1F1FA    | x5 <= 1F1FA064 
    ##################

    print("\n\nTESTING AUIPC\n\n")

    # Check test's init state
    assert binary_to_hex(dut.instruction.value) == "1F1FA297"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    # auipc x5 0x1F1FA
    assert binary_to_hex(dut.regfile.registers[5].value) == "1F1FA068"

    ##################
    # LUI TEST
    # 2F2FA2B7  //LUI TEST START :    lui x5 0x2F2FA      | x5 <= 2F2FA000
    ##################
    print("\n\nTESTING LUI\n\n")
    # Check test's init state
    assert binary_to_hex(dut.instruction.value) == "2F2FA2B7"

    await RisingEdge(dut.clk) # lui x5 0x2F2FA 
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[5].value) == "2F2FA000"

    ##################
    # FFF9AB93  //SLTI TEST START :   slti x23 x19 0xFFF  | x23 <= 00000000
    # 001BAB93  //                    slti x23 x23 0x001  | x23 <= 00000001
    ##################

    print("\n\nTESTING SLTI\n\n")
    assert binary_to_hex(dut.regfile.registers[19].value) == "00000AAA"
    assert binary_to_hex(dut.instruction.value) == "FFF9AB93"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[23].value) == "00000000"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[23].value) == "00000001"

    ##################
    # FFF9BB13  //SLTIU TEST START :  sltiu x22 x19 0xFFF | x22 <= 00000001
    # 0019BB13  //                    sltiu x22 x19 0x001 | x22 <= 00000000
    ##################
    assert binary_to_hex(dut.instruction.value) == "FFF9BB13"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[22].value) == "00000001"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[22].value) == "00000000"



    #xori test
    print("\n\nTESTING XORI\n\n")
    assert binary_to_hex(dut.instruction.value) == "AAA94913"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[18].value) == "21524445"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert (
        binary_to_hex(dut.regfile.registers[19].value) ==
        binary_to_hex(dut.regfile.registers[18].value)
    )


    #ori test
    print("\n\nTESTING ORI\n\n")
    assert binary_to_hex(dut.regfile.registers[19].value) == "21524445" # checking the initial state
    assert binary_to_hex(dut.instruction.value) == "AAA9EA13"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[20].value) == "FFFFFEEF"
    assert binary_to_hex(dut.instruction.value) == "000A6A93"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[21].value) == "FFFFFEEF"



    #andi test
    print("\n\nTESTING ANDI\n\n")
    assert binary_to_hex(dut.regfile.registers[18].value) == "21524445"
    assert binary_to_hex(dut.regfile.registers[20].value) == "FFFFFEEF"
    assert binary_to_hex(dut.instruction.value) == "7FFA7913"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[18].value) == "000006EF"
    assert binary_to_hex(dut.instruction.value) == "FFFAF993"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[19].value) == "FFFFFEEF"
    assert binary_to_hex(dut.instruction.value) == "000AFA13"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[20].value) == "00000000"

    # slli test
    print("\n\nTESTING SLLI\n\n")
    assert binary_to_hex(dut.regfile.registers[26].value) == "DEADC09A"
    assert binary_to_hex(dut.instruction.value) == "00499993"
    await RisingEdge(dut.clk)
    await Timer(1, units = "ns")
    assert binary_to_hex(dut.regfile.registers[19].value) == "FFFFEEF0"
    assert binary_to_hex(dut.instruction.value) == "02499993"
    await RisingEdge(dut.clk)

    #srli test
    print("\n\nTESTING SRLI\n\n")
    assert binary_to_hex(dut.instruction.value) == "0049DA13"
    assert binary_to_hex(dut.regfile.registers[26].value) == "DEADC09A"
    await RisingEdge(dut.clk)
    assert Timer(1, units = "ns")

    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "404ADA93"
    assert binary_to_hex(dut.regfile.registers[20].value) == "0FFFFEEF"

    #srai test
    print("\n\nSRAI TEST\n\n")

    assert binary_to_hex(dut.instruction.value) == "404ADA93"

    assert binary_to_hex(dut.regfile.registers[25].value) == "7F4FD38B"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[21].value) == "FFFFFFEE"
    assert binary_to_hex(dut.instruction.value) == "424ADA93"
    await RisingEdge(dut.clk)


    ##################
    # 412A8933  //SUB TEST START :    sub x18 x21 x18     | x18 <= FFFFF8FF
    ##################
    print("\n\nTESTING SUB\n\n")
    assert binary_to_hex(dut.instruction.value) == "412A8933"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFFFF8FF"




    print("\n\nTESTING SLL\n\n")
    assert binary_to_hex(dut.instruction.value) == "00800393"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "00791933" 
    assert binary_to_hex(dut.regfile.registers[7].value) == "00000008"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"





    print("\n\n TESTING SLT\n\n")
    assert binary_to_hex(dut.instruction.value) == "013928B3"
    assert binary_to_hex(dut.regfile.registers[23].value) == "00000001"
    assert binary_to_hex(dut.regfile.registers[22].value) == "00000000"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[17].value) == "00000001"

    print("\n\n Testing SLTU\n\n")
    assert binary_to_hex(dut.instruction.value) == "013938B3"
    assert binary_to_hex(dut.regfile.registers[23]) == "00000001"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[17]) == "00000001"

    print("\n\n Testing XOR")
    assert binary_to_hex(dut.instruction.value) == "013948B3"
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"
    assert binary_to_hex(dut.regfile.registers[19].value) == "FFFFEEF0"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[17].value) == "000711F0"

    print("\n\n TESTING SRL\n\n")
    assert binary_to_hex(dut.instruction.value) == "0079D433"
    assert binary_to_hex(dut.regfile.registers[7]) == "00000008"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[8].value) == "00FFFFEE"

    print("\n\n TESTING SRA\n\n")
    assert binary_to_hex(dut.instruction.value) == "4079D433"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.regfile.registers[8].value) == "FFFFFFEE"


    print("\n\nTESTING BLT\n\n")
    assert binary_to_hex(dut.instruction.value) == "0088C463"
    assert binary_to_hex(dut.regfile.registers[8].value) == "FFFFFFEE"
    assert binary_to_hex(dut.regfile.registers[17].value) == "000711F0"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "01144463"
    await RisingEdge(dut.clk) # blt x8 x17 0x8
    assert not binary_to_hex(dut.instruction.value) == "00C00413"
    assert binary_to_hex(dut.regfile.registers[8].value) == "FFFFFFEE"

    print("\n\nTESTING BNE\n\n")

    assert binary_to_hex(dut.instruction.value) == "00841463"
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"
    assert binary_to_hex(dut.regfile.registers[8].value) == "FFFFFFEE"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "01141463"
    await RisingEdge(dut.clk)
    assert not binary_to_hex(dut.instruction.value) == "00C00413"

    print("\n\nTESTING BGE\n\n")

    assert binary_to_hex(dut.instruction.value) == "01145463"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "00845463"
    await RisingEdge(dut.clk)
    assert not binary_to_hex(dut.instruction.value) == "00C00413"
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"

    print("\n\nTESTING BLTU\n\n")
    assert binary_to_hex(dut.instruction.value) == "01146463"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "0088E463"
    await RisingEdge(dut.clk)
    assert not binary_to_hex(dut.instruction.value) == "00C00413"
    assert binary_to_hex(dut.regfile.registers[8]) == "FFFFFFEE"

    print("\n\nTESTING BGEU\n\n")
    assert binary_to_hex(dut.instruction.value) == "0088F463"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "01147463"
    await RisingEdge(dut.clk)
    assert not binary_to_hex(dut.instruction.value) == "00C00413"
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"

    print("\n\n TESTING JALR\n\n") 
    assert binary_to_hex(dut.instruction.value) == "00000397"
    assert binary_to_hex(dut.pc.value) == "00000110"

    await RisingEdge(dut.clk) # auipc x7 0x00 
    await RisingEdge(dut.clk) # addi x7 x7 0x10 
    assert binary_to_hex(dut.regfile.registers[7].value) == "00000124"

    await RisingEdge(dut.clk) # jalr x1  -4(x7)
    assert binary_to_hex(dut.regfile.registers[1].value) == "0000011C"
    assert not binary_to_hex(dut.instruction.value) == "00C00413"
    assert binary_to_hex(dut.regfile.registers[8].value) == "FFFFFFEE"
    assert binary_to_hex(dut.pc.value) == "00000120"

    print("\n\nTESTING SB\n\n")
    assert binary_to_hex(dut.instruction.value) == "008020A3"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "00818323"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.data_memory.mem[1].value) == "00EE0000"

    print("\n\nTESTING SH\n\n")
    assert binary_to_hex(dut.instruction.value) == "008010A3"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "008011A3"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.instruction.value) == "00819323"
    await RisingEdge(dut.clk)
    assert binary_to_hex(dut.data_memory.mem[1].value) == "FFEE0000"

    print("\n\nTESTING LB\n\n")

    # Check test's init state
    assert binary_to_hex(dut.instruction.value) == "01018393"

    await RisingEdge(dut.clk) # addi x7 x0 0x10 
    assert binary_to_hex(dut.regfile.registers[7].value) == "00001010"

    await RisingEdge(dut.clk) # lw x18 -1(x7)
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFF8FF00"

    await RisingEdge(dut.clk) # lb x18 -1(x7) 
    assert binary_to_hex(dut.regfile.registers[18].value) == "FFFFFFDE"

    await RisingEdge(dut.clk) # lbu x19 -3(x7)
    assert binary_to_hex(dut.regfile.registers[19].value) == "000000BE"

    await RisingEdge(dut.clk) # lh x20 -3(x7) 
    assert binary_to_hex(dut.regfile.registers[20].value) == "0FFFFEEF"

    await RisingEdge(dut.clk) # lh x20 -6(x7)
    assert binary_to_hex(dut.regfile.registers[20].value) == "FFFFDEAD"

    await RisingEdge(dut.clk) # lhu x21 -3(x7) 
    assert binary_to_hex(dut.regfile.registers[21].value) == "FFFFFFEE"

    await RisingEdge(dut.clk) # lhu x21 -6(x7)
    assert binary_to_hex(dut.regfile.registers[21].value) == "0000DEAD"
