[pytest]
addopts = 
    --simulator=verilator
    --verilog-sources=../../src/regfile.sv
    --top-module=regfile
testpaths = .
python_files = *_verification.py test_*.py
python_classes = Test*
python_functions = test_* *_test
